name: Feature request
description: Something GroundTrace should be able to do
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What can't you find out about your app today?
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: What you have in mind
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What you've tried instead
